name: Upload CodeCov Report
on: [push, pull_request]
jobs:
  run:
    runs-on: windows-latest
    name: Build, Test , Upload Code Coverage Report
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: ‘2’
        id: checkout_code
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        id: setup_msbuild
      - name: Run MSBuild
        id: run_msbuild
        run: msbuild /p:Configuration=Debug /p:Platform=x86 HelloCovDemo.sln
      - name: Setup VSTest and add to PATH
        uses: darenm/Setup-VSTest@v1
        id: setup_vstest
      - name: Setup OpenCppCoverage and add to PATh
        id: setup_opencppcoverage
        run: |
          choco install OpenCppCoverage -y
          echo "C:\Program Files\OpenCppCoverage" >> $env:GITHUB_PATH
      - name: Generate Report
        id: generate_test_report
        shell: cmd
        run: OpenCppCoverage.exe --sources HelloCov --export_type cobertura:HelloCov.xml -- "vstest.console.exe" Debug\HelloTest.dll
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          files: ./HelloCov.xml
          fail_ci_if_error: true
          functionalities: fix
      - name: Ponicode Unit Test
        # You may pin to the exact commit or the version.
        # uses: ponicode/unit-testing-action@ab61a5a8e527affa366dda30d40fb205147b2513
        uses: ponicode/unit-testing-action@0.0.1-christmas
        with:
          # Path of repo to generate unit tests for
          repoPath: ./
          # Ponicode token to use Ponicode API
          authToken: true
          changedFilesOnly: false
